### ISSUE TITLE
Document heading floating issue

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#102]
Sometimes during the loading of Detail table in Documents Heading we get an error from backend
"Cannot set property of 'documentType' of undefined. 
http://joxi.ru/xAeNweNspG4DWr

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/74

**Comment by robtweed** [comment]
See if it's fixed now on dev

Rob

**Comment by anna-otrokhova** [comment]
@robtweed 
Ok. Thank you. I will check tomorrow.

**Comment by anna-otrokhova** [comment]
It works. Thank you.
