### ISSUE TITLE
Clinical Query issue with empty data

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#109]
1) Sometimes we get the broken data like this: http://prntscr.com/i5fg9l
Here is the request: http://prntscr.com/i5fha9

Could you check it please?
Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/78

**Comment by robtweed** [comment]
OK this was due to an invalid patient reference on EtherCIS.  I've added a check to the search logic that should prevent this in future.  Both dev and showcase updated
