### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by devmikey** [PulseTile/PulseTile-React#169]
Getting the following error when running npm run start.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function

Is there an issue with the webpack config.

I'm developing under Windows and haven't installed the full stack at this stage.

**Comment by tony-shannon** [comment]
thanks @devmikey 

@kbeloborodko could you please offer advice on this one?

thanks
Tony

**Comment by devmikey** [comment]
Resolved this - see issue reported at [https://github.com/vuejs-templates/webpack-simple/issues/136](url)

**Comment by tony-shannon** [comment]
thank you @devmikey
