### ISSUE TITLE
Feeds not loading

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React#302]
On http://dev.ripple.foundation:8000 Feeds are not loading. 
Assume that problem in cross-domain requests: https://www.screencast.com/t/NlxlcU2mwvS6

Also, noticed one thing. All Feeds has Remote Address: 217.198.117.111:443 . 
Tried to go to this address but got this error message:

400 Bad Request
The plain HTTP request was sent to HTTPS port

**Comment by PhilBarrett** [comment]
@kuvakina I believe this is in the wrong repo. Can you move onto Helm please.

**Comment by kuvakina** [comment]
Done, sorry

**Comment by PhilBarrett** [comment]
https://github.com/LeedsCC/Helm-PHR-Project/issues/87
