### ISSUE TITLE
Add processing of PUT request for Allergies Heading

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#44]
Add processing of PUT request for Allergies Heading

This issue may be linked to the existing one: https://github.com/RippleOSI/Ripple-Qewd/issues/39
https://github.com/PulseTile/PulseTile/issues/48

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova 

helpful to have that here,
suggest you also need to link this to the related issue on QEWD-Ripple, as there is a dependency there that Rob needs to address
please take a look here;
https://github.com/RippleOSI/Ripple-Qewd/issues

this may be the one you need to link to.. 
https://github.com/RippleOSI/Ripple-Qewd/issues/39
Always worth considering if existing/new issue needs to be linked elsewhere from issues raised here
thanks
Tony

**Comment by anna-otrokhova** [comment]
@tony-shannon 
This issue was fixed only on React version for now. 
Tony, can I close this issue here?

**Comment by tony-shannon** [comment]
yes
 thanks
