### ISSUE TITLE
Block 3. MDT Heading

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#71]
To do

**Comment by tony-shannon** [comment]
thanks
when the time comes to close this, please include link to the relevant commit
thanks
T

**Comment by anna-otrokhova** [comment]
We have finished the developing of this heading on React version.
The creation and editing functionality has an issue https://github.com/PulseTile/PulseTile-React/issues/74 

The link to the relevant commit ->  https://github.com/PulseTile/PulseTile-React/commit/fbf40e7ab3a1750dcf5142221315f6a451860387
