### ISSUE TITLE
MDT heading can't be neither created nor updated on dev and showcase boxes

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#74]
We have checked and figured out that, MDT doesn't work as well both creation and editing. Let me prepare the screen:
PUT: https://prnt.sc/hiwf1k
log: https://prnt.sc/hiwew1
POST: https://prnt.sc/hiw7qk

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/66
https://github.com/PulseTile/PulseTile/issues/61

**Comment by robtweed** [comment]
This is because no POST configuration has ever been defined for MDT Reports in the past.

I can, however, use this information from Ian to add the POST/PUT mappings for MDT reports

https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/MDT/mdt_report_1.1.0.md

**Comment by anna-otrokhova** [comment]
@robtweed 
Thank you, Rob.
Please add it.

**Comment by robtweed** [comment]
I'll need to discuss some issues with Ian to clarify the Flat JSON, and to make sure you send the correct fields / values to create / edit an MDT Report record.  I'll contact Ian next week

**Comment by robtweed** [comment]
OK, with Ian's help, MDT Reports should be able to created and updated.  Just make sure you send the following fields:

 dateOfMeeting   (JavaScript Date getTime() format)
 serviceTeam   (text)
 dateOfRequest   (JavaScript Date getTime() format)
 question (text)
 notes  (text)
 author (optional)

Please confirm if it works or if it still has problems

Rob

Rob

**Comment by anna-otrokhova** [comment]
@robtweed 
I have tested with our initial request and only with proposed by you fields.
Unfortunately, it doesn't work still.
PUT: http://prntscr.com/i4fnd2
POST: http://prntscr.com/i4fohy 
POST with mentioned fields in postman:
{"userId":"9999999000","serviceTeam":"test","question":"test","notes":"test","dateOfRequest":"1512432000000","dateOfMeeting":"1514844000000"}

Could you please check it again?

**Comment by anna-otrokhova** [comment]
@robtweed 
Today PUT request works, but the fields dateOfRequest and

**Comment by anna-otrokhova** [comment]
@robtweed 
I have tested today again, PUT works in general, only fields dateOfRequest and servicePageLink
can't changed:
PUT: http://prntscr.com/i4vdl1
GET after PUT: http://prntscr.com/i4veta 

POST doesn't work t all.

**Comment by robtweed** [comment]
OK try again.  The AQL needed fixing, so records weren't being retrieved from EtherCIS.

By the way it looked like you also had the old problem of trying to fetch mdtreporrts again before EtherCIS had a chance to save the new record - please check the UI logic.

I don't know why dateOfRequest wouldn't be updated - can you check again and let me know if it works or still fails.

servicePageLink isn't a field in the MDT Reports template on OpenEHR.  Don't know what this field is or what it's supposed to do.  We'll need to find out from Tony

Rob

**Comment by anna-otrokhova** [comment]
Ok. It works.
