### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#78]
In process
1) ui-elements (3):
- PTButton
- PTPanel
- Spinner

2) presentational (5):
- Footer
- MainLogo
- PaginationBlock
- Sidebar
- NotificationContent

3) Fields (9)
- CustomInputCheckbox
- CustomInputInline
- DateInput
- FileInput
- StaticFormField
- ValidatedTextareaFormGroup
- ValidatedInputFormGroup
- SelectFormGroup
- RangeInput

4) Containers (32)
- AdvancedPatientSearch
- AdvancedPatientSearchForm
- App
- BasicPatientSearch
- Breadcrumbs
- Header
- HeaderTitle
- HeaderToolbar
- Main
- MainSpinner
- NavSearch
- SearchOptions
- PatientsChart
- PatientAccessDisclaimerModal
- PatientsList
- ViewPatienDropdown
- ViewPatientDropdownOptions
- PTCustomCheckbox
- PatientsInfoPanel
- PatientsListHeader
- SortableTable
- SortableTableEmptyDataRow
- SortableTableHoveredRow
- SortableTablePatients
- SortableTableRow
- SortableTableHeaderCell
- SortableTableHeaderRow
- TopHeader
- UserPanel
- UserPanelItem
- UserAccountPanel

5) Plugins-page-components (5)
- PluginCreate
- PluginDetailHeader
- PluginDetailPanel
- PluginListHeader
- PluginMainPanel

6) Plugins (74)
- Allergies
- AllergiesCreateForm
- AllergiesDetail
- AllergyDetailMainForm
.
- ClinicalNotes
- ClinicalNotesCreateForm
- ClinicalNotesDetail
- ClinicalNotesDetailForm
.
- Contacts
- ContactsCreateForm
- ContactsDetail
- ContactsDetailForm
.
- Events
- EventsCreateForm
- EventsDetail
- EventsDetailForm
- EventsDetailPanel
- EventsListHeader
- EventsMainPanel
- EventsTimelines
.
- GenericPlugin
- GenericPluginCreateForm
- GenericPluginDetail
- GenericPluginDetailForm
.
- MDTs
- MDTsCreateForm
- MDTsDetail
- MDTsDetailForm
.
- Medications
- MedicationsCreateForm
- MedicationsDetail
- MedicationsDetailForm
- MedicationsDetailPanel
- MedicationsPrescriptionForm
.
- Orders
- OrdersCreateForm
- OrdersSelectable
- OrdersDetail
.
- PersonalNotes
- PersonalNotesCreateForm
- PersonalNotesDetail
- PersonalNotesDetailForm
.
- ProblemsDiagnosis
- ProblemsDiagnosisCreateForm
- ProblemsDiagnosisDetail
- ProblemsDiagnosisDetailForm
.
- Procedures
- ProceduresCreateForm
- ProceduresDetail
- ProceduresDetailForm
.
- Referrals
- ReferralsCreateForm
- ReferralsDetail
- ReferralsDetailForm
.
- Vaccinations
- VaccinationCreateForm
- VaccinationDetail
- VaccinationDetailForm
.
- TestResults
- TestResultsDetail
.
- PatientsLists
- PatientsFullDetailsSearch
- SystemDashboard
.
- PatientsSummary
- PatientsSummaryListHeader
- PatientsSummaryPanel
- PTCustomCheckbox
- SimpleDashboardPanel
.
- UserProfile
- AppSettingsForm
- ContactForm
- PersonalForm
- PersonalInformationPanel

**Comment by ahoncharov** [comment]
https://github.com/PulseTile/PulseTile-React/commit/e757f515a48377edca0c186563a49b34ed2cbdce

**Comment by anna-otrokhova** [comment]
Done http://dev.ripple.foundation/coverage/

**Comment by tony-shannon** [comment]
Great, please add istanbul coverage badge to github repo
as per this
http://maximilianschmitt.me/posts/istanbul-code-coverage-badge-github/

We have a travisCI account for Ripple already
https://travis-ci.org/PulseTile/PulseTile

thanks
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Ok. We will do it and let you know once done.

**Comment by ahoncharov** [comment]
Add tests for Documents Heading. - https://github.com/PulseTile/PulseTile-React/commit/4db3b002c0ff9fac30d0e726ba525d306ab34915
