### ISSUE TITLE
Drawing Heading - floating issue while editing

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#83]
Recently we were working on Drawing Heading and found some issue which we need some assistance with to figure out how to fix it.  
Here are my steps :
1) http://prntscr.com/hsxq35  --- already broken picture, I go to edit it
2) http://prntscr.com/hsxqlk   --- I edit, and click Complete
3) http://prntscr.com/hsxqyo   --- here is the picture I’ve sent
4) I look at the online service whether it is valid --->
http://prntscr.com/hsxrjv  ---> the picture is normal
5) Get response came broken up http://prntscr.com/hsxrvk 
6) I look at the Get request ->
http://prntscr.com/hsxs6e 
http://prntscr.com/hsxsa4 
7) I check the validity of the incoming line base64 ->
http://prntscr.com/hsxsyi   ---> it came not valid already
8) What else I noticed --->
http://prntscr.com/hsxtcj  ---> I copied this line into Put and looked whether it's in Get
http://prntscr.com/hsxvcz  --->
it seems that either the Get request stores a string with Put then puts “…” and adds some more characters to the string, accordingly the URL becomes non-valid and the picture can’t be displayed, or contains a fully identical string from the PUT and adds more characters. 

The issue is floating while editing, I usually face it when I just press edit (I even don't change anything ) and then press 'complete". The picture is crashed in most of the cases.

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/73

**Comment by robtweed** [comment]
Try editing the drawing again.  I think it should save the updated version correctly now

Rob

**Comment by anna-otrokhova** [comment]
@robtweed 
Ok. Thank you. I will check tomorrow.

**Comment by anna-otrokhova** [comment]
@robtweed 
Thank you. It works.
