### ISSUE TITLE
Add “Loading..” note for each table on Patient Summary page. 

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#88]
Add “Loading..” note for each table on Patient Summary page. We suppose it can look like this in each table while it is loading http://prntscr.com/hw0tt3 and in case there are no results user will see such note http://prntscr.com/hw0vc5 .

**Comment by ahoncharov** [comment]
https://github.com/PulseTile/PulseTile-React/commit/5d05c0732afb8a0394bfdd8b5e44bae01f82a1ff

**Comment by tony-shannon** [comment]
thanks Alexey, that is a pull request/commit?

**Comment by ahoncharov** [comment]
It is commit - https://github.com/PulseTile/PulseTile-React/commit/5d05c0732afb8a0394bfdd8b5e44bae01f82a1ff
"Refactoring PatientsSummary configs. Add 'Loading ...' to load data in the boards"

**Comment by tony-shannon** [comment]
thanks Anna
Good idea to add that detail so others can understand the thread
thanks
T

**Comment by anna-otrokhova** [comment]
Done
