### ISSUE TITLE
Transfers of Care

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#90]
Edit functionality doesn't work. (PUT)
Could you please check it: http://prntscr.com/i86npg

Related issue: https://github.com/PulseTile/PulseTile/issues/64 
https://github.com/RippleOSI/Ripple-Qewd/issues/67

**Comment by ahoncharov** [comment]
https://github.com/PulseTile/PulseTile-React/commit/50c8b907f8672f8ca0e4dcb953cd4dd7dc387d99 - Add TransfersOfCare list and detail.
https://github.com/PulseTile/PulseTile-React/commit/d6dd6ba22afe0491cdaff1f95eca0be6da09afeb - Add TransfersOfCare edit.
https://github.com/PulseTile/PulseTile-React/commit/b0f7e776efdd2e5ef629fe74455120911e0bc7c1 - Add Service of TransfersOfCare.
https://github.com/PulseTile/PulseTile-React/commit/51f9b5a02bf8f5cceeab4e6517e25b1efb791512 - Change Transfer Of Care Edit.
https://github.com/PulseTile/PulseTile-React/commit/f3abe10a7f7a2ea3e7c02b3a61461a74775ea922 - Change Edit Records for Transfers Of Care.
https://github.com/PulseTile/PulseTile-React/commit/357cff329ebd1dc30b190c7fd340823ddd1a9135 - Add Drag and Drop functionality. Add validation and forms send Data to request on the Transforms of Care page.
https://github.com/PulseTile/PulseTile-React/commit/882eb4c3ff4fbc987cb681d82b1c9edc4ae60504 - Add Transfers of Care Popover

**Comment by anna-otrokhova** [comment]
Edit functionality doesn't work. (PUT)
Please check it. http://prntscr.com/i86npg

**Comment by robtweed** [comment]
Try PUT /api/patients/:patientId/events/toc/:sourceId   (edit Transfer of Care) on dev now and let me know if it works OK

**Comment by anna-otrokhova** [comment]
it works, thank you
