### ISSUE TITLE
Clinical statements heading

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#94]
to do

**Comment by anna-otrokhova** [comment]
Done and discussed with Phil on call.

**Comment by PhilBarrett** [comment]
Final query following further testing. 

When I am in the search box and hit the spacebar a list of possible entries doesn't appear. When i enter a character it works fine, but the spacebar function isn't there.  

![screen shot 2018-03-01 at 17 15 46](https://user-images.githubusercontent.com/12699244/36861678-7ced1e80-1d7c-11e8-8f3d-1c55148053b4.png)

**Comment by kbeloborodko** [comment]
@PhilBarrett could you please recheck this issue in the dev environment?

**Comment by PhilBarrett** [comment]
Thanks @kbeloborodko

**Comment by tony-shannon** [comment]
I've rechecked it, working ok
